### ISSUE TITLE
大哥好

### ISSUE THREAD

**Issue by xiaopohou** [fawdlstty/SimpleMS#1]
非常感谢您的贡献，给你一个大赞，其次我刚才看了你的这个微服务框架介绍，仔细的看了一遍，现在不是已经有consul了吗，你这个是处于什么想法做的呢？有现成的呀！

**Comment by fawdlstty** [comment]
这是一个微服务实现demo，用于验证原型，不用于生产环境

**Comment by xiaopohou** [comment]
哦哦，感谢哥哥的回复，那我知道了，我想问一下你有所谓的微服务core的项目分享吗，小弟想学习一下正规军大佬们如何架构的！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fawdlstty"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 凌晨0:59
收件人:&nbsp;"fawdlstty/SimpleMS"<SimpleMS@noreply.github.com&gt;;
抄送:&nbsp;"└Monkey丶"<393331943@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fawdlstty/SimpleMS] 大哥好 (#1)





 
这是一个微服务实现demo，用于验证原型，不用于生产环境

**Comment by fawdlstty** [comment]
这个建议看微软官网学习。我算野路子，不是正规的

**Comment by xiaopohou** [comment]
好吧！谢谢哥！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fawdlstty"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 上午9:46
收件人:&nbsp;"fawdlstty/SimpleMS"<SimpleMS@noreply.github.com&gt;;
抄送:&nbsp;"└Monkey丶"<393331943@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fawdlstty/SimpleMS] 大哥好 (#1)





 
这个建议看微软官网学习。我算野路子，不是正规的
